# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Twio
tagline:          'An Indian Safari'
description:      'A design and development related blog with the main focus on Ruby, Rails and Emberjs. '
url:              http://www.twio.github.io
baseurl:          /

author:
  name:           'Arpit Shah'
  url:            https://www.github.com/collegeimprovements

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/collegeimprovements